name: interfaz_inicio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-170.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.6.2 # VersiÃ³n actualizada del paquete
  google_maps_flutter: ^2.0.10 # VersiÃ³n actualizada del paquete
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: 5.0.0-nullsafety.0 # Actualizada a la Ãºltima versiÃ³n
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

